const page=(location.pathname.split('/').pop()||'index.html');
const header=document.querySelector('#siteHeader');
if(header) header.innerHTML=`<header class="nav-wrap"><nav class="nav shell" aria-label="Main navigation"><a class="brand logo-brand" href="index.html"><img src="assets/al-saad-logo.png" alt=""><span>ASIS <b>MUN</b><small>2026</small></span></a><button class="menu-btn" aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button><div class="nav-links"><a href="about.html">About</a><a href="committees.html">Committees</a><a href="secretariat.html">Secretariat</a><a href="resources.html">Resources</a><a href="faq.html">FAQ</a><a href="contact.html">Contact</a><a class="nav-cta" href="register.html">Register <span>↗</span></a></div></nav></header>`;
const footer=document.querySelector('#siteFooter');
if(footer) footer.innerHTML=`<footer><div class="shell footer-top"><div class="footer-brand"><img class="footer-logo" src="assets/al-saad-logo.png" alt="Al Saad Indian School logo"><h2>ASIS MUN <span>2026</span></h2><p>Empowering Student Voices for Global Change</p></div><div><small>NAVIGATE</small><a href="about.html">About</a><a href="committees.html">Committees</a><a href="secretariat.html">Secretariat</a><a href="register.html">Register</a></div><div><small>DELEGATE DESK</small><a href="resources.html">Resources</a><a href="faq.html">FAQ</a><a href="contact.html">Contact</a><a href="index.html">Home</a></div></div><div class="shell footer-bottom"><span>© 2026 ASIS MUN Secretariat</span><span>Al Saad Indian School</span><a href="#">Back to top ↑</a></div></footer>`;
document.querySelectorAll('.nav-links a').forEach(a=>{if(a.getAttribute('href')===page)a.classList.add('active')});
const committees=[
['DISEC','Disarmament & International Security','Autonomous Weapon Systems & AI in Combat','Establishing a global framework to regulate autonomous kinetic weapons and algorithmic targeting in urban warfare.','20–25'],
['ECOFIN','Economic & Financial Committee','Critical Mineral Supply Chains','Securing rare earth elements for the global energy transition amid trade restrictions and resource nationalism.','20–25'],
['UNGA','United Nations General Assembly','Illicit Financial Flows','Resolving jurisdictional loopholes in offshore tax havens to stabilise national economies.','20–25'],
['SOCHUM','Social, Humanitarian & Cultural','Human Rights in the Digital Age','Safeguarding biometric privacy, surveillance data, and the right to anonymity.','20–25'],
['UNSC','United Nations Security Council','Resource Wars & Critical Minerals','Addressing threats to peace arising from conflict over rare earth elements and deep-sea mining rights.','20–25'],
['UNEP','UN Environment Programme','Geoengineering & Climate Intervention','Regulating unilateral solar radiation modification and marine cloud brightening experiments.','20–25'],
['UNHCR','UN High Commissioner for Refugees','Climate-Induced Displacement','Revising refugee protections for climate-displaced persons and citizens of sinking states.','20–25'],
['IP','International Press','Deepfakes & Information Warfare','Safeguarding journalistic integrity and public trust amid synthetic media in conflict zones.','15–20'],
['F1 WMSC','Formula 1 World Motor Sport Council','2030 Sustainability Regulations','Transitioning to fully sustainable synthetic fuels without compromising engine performance.','20–25'],
['FIFA','FIFA Executive Committee','Future World Cup Host Selection','Creating ethical, human-rights, and environmental standards for future tournament bids.','20–25']];
const team=[['AK','Abhiram Krishna','Secretary General'],['AG','Abhinav Girisankar','USG Policy'],['TD','Tanmay Deepak','USG Delegate Affairs'],['KK','Keerthana Karella','USG Finance'],['KP','Krishnapriya','OC Head'],['DV','David Varughese','USG Marketing'],['SA','Shreya Aswathy','USG Design'],['AA','Aditi Abhilash','USG Logistics'],['SP','Shelbino Paul','USG Technology']];
const faqs=[['What is ASIS MUN?','ASIS MUN is a student-led Model United Nations conference where delegates represent countries, debate global challenges, and build resolutions.'],['Who can participate?','The conference welcomes students in Grades 7–12, including inter-school participants. Further eligibility details will be published with registration.'],['When is the conference?','The current proposed conference dates are 24–25 October 2026. Any confirmed schedule update will be posted here.'],['How do I register?','An official online application link from Delegate Affairs will be added to the Registration page once it is ready.'],['What committees are available?','The conference includes seven UN-style committees, International Press, Formula 1 WMSC, and the FIFA Executive Committee.'],['Where can I find study guides?','Study guides, committee handbooks, Rules of Procedure, and training details will be released on the Resources page.']];
const grid=document.querySelector('#committeeGrid');
if(grid) committees.forEach((c,i)=>{const b=document.createElement('button');b.className='committee-card';b.innerHTML=`<small>${String(i+1).padStart(2,'0')}</small><div><h3>${c[0]}</h3><p>${c[1]}</p></div><span>↗</span>`;b.onclick=()=>openCommittee(c);grid.appendChild(b)});
const teamGrid=document.querySelector('#teamGrid');
if(teamGrid) teamGrid.innerHTML=team.map(t=>`<article class="team-card"><div class="initial">${t[0]}</div><small>${t[2]}</small><h3>${t[1]}</h3></article>`).join('');
const faqList=document.querySelector('#faqList');
if(faqList){faqList.innerHTML=faqs.map(f=>`<div class="faq-item"><button class="faq-q" aria-expanded="false">${f[0]}<span>＋</span></button><div class="faq-a">${f[1]}</div></div>`).join('');document.querySelectorAll('.faq-q').forEach(q=>q.onclick=()=>{const p=q.parentElement,o=p.classList.toggle('open');q.setAttribute('aria-expanded',o)})}
const modal=document.querySelector('#committeeModal');
function openCommittee(c){if(!modal)return;document.querySelector('#modalContent').innerHTML=`<div class="modal-body"><div class="code">${c[0]}</div><h2>${c[1]}</h2><div class="modal-agenda"><small>PROVISIONAL AGENDA</small><h3>${c[2]}</h3><p>${c[3]}</p></div><div class="modal-tags"><span>Grades 7–12</span><span>${c[4]} delegates</span><span>Chairs: Coming soon</span><span>Study guide: Coming soon</span></div></div>`;modal.showModal()}
if(modal){document.querySelector('.modal-close').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()}}
const menu=document.querySelector('.menu-btn');
if(menu){const closeMenu=()=>{document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false')};menu.onclick=()=>{const o=document.body.classList.toggle('menu-open');menu.setAttribute('aria-expanded',o)};document.querySelectorAll('.nav-links a').forEach(a=>a.onclick=closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});window.addEventListener('resize',()=>{if(innerWidth>850)closeMenu()})}
const form=document.querySelector('#contactForm'),toast=document.querySelector('.toast');
if(form) form.onsubmit=e=>{e.preventDefault();form.classList.add('sent');if(toast){toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3500)}};
